### PR TITLE
Add support for Server Side Sorting

### PR DESCRIPTION
**Pull request by psoreide**

### CODE REVIEW

**Comment by gabibeyo** [comment]
@psoreide hello,
Can you please send your email address to my mail?
gabi.beyo@imperva.com

I would like to ask something.

**Comment by gabibeyo** [comment]
@psoreide Can you send a snippet with how it looks like from a consumer perspective?
How the API is consumed? (I can imagine but would like to make sure we are on the same page)

**Comment by psoreide** [comment]
Here is example of sorting:
`    private static void useCase11() {
        Endpoint endpoint = createEndpoint();
        QueryRequest queryRequest = createQueryRequest(endpoint);

        queryRequest.setPageChunkSize(100); //* PAGING

        queryRequest.addSortKey(FieldType.LAST_NAME); //* SORTING - Last Name ascending
        queryRequest.addSortKey(FieldType.FIRST_NAME).setReverseOrder(true); //* SORTING - First Name descending

        queryRequest.addSearchSentence(new QueryAssembler().addPhrase(FieldType.FIRST_NAME, PhraseOperator.EQUAL, "Gabriel").closeSentence());

        QueryResponse result = new QueryResponse();
        try(Connector connector = new Connector(queryRequest)) {
            Cursor cursor = connector.getCursor();
            while (cursor.hasNext()) {
                result.addPartitionResponse(cursor.next().get());
            }
        }

        System.out.println("Use Case 11 - Sorting:");
        for (EntityResponse entityResponse : result.getAll()) {
            for (Field field : entityResponse.getValue()) {
                System.out.println("Val: " + field.getValue());
            }
        }
    }
`

**Comment by gabibeyo** [comment]
I made some minor changes, I would like to add this to the next release version but I still can't see that the sort works like expected. I am playing with the sorting values but still, it seems that nothing affects the sort.
Could it be that my MS Active Directory Server doesn't support the Sorting Control?

**Pull request merged**
